### ISSUE TITLE
Python Error When Running main.py With Python 3.10

### ISSUE THREAD

**Issue by pwnllc** [Joensw/Reddit-Shorts-Bot#6] opened 2023-08-23 22:28 UTC
`Traceback (most recent call last):
  File "/home/user/Reddit-Shorts-Bot/main.py", line 95, in <module>
    main()
  File "/home/user/Reddit-Shorts-Bot/main.py", line 84, in main
    create_videos()
  File "/home/user/Reddit-Shorts-Bot/main.py", line 39, in create_videos
    proc = subprocess.run(cmd.as_posix())
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python /home/user/RedditVideoMakerBot-master/main.py'
`

**Comment by Joensw** [comment] 2023-08-24 05:16
I'm looking into it. Unfortunately, the newest version of the Reddit-Video-Maker-Bot is not running correctly for me, so till I get that working I can't test anything.

**Comment by Joensw** [comment] 2023-08-24 05:43
Alright, I got it working. Which Operating System are you using?

**Comment by pwnllc** [comment] 2023-08-24 11:22
Hi, I am using Linux (Parrot OS)

**Comment by pwnllc** [comment] 2023-08-25 09:30
So what did you do to get it working?

**Comment by Joensw** [comment] 2023-08-25 09:55
Sorry, that comment was just about the reddit video maker bot itself. It took a while to get that working. I've managed to reproduce the problem you have, but haven't found a fix yet. There seems to be an issue with the paths and program call under Linux. I'll have more time this weekend .

**Comment by Joensw** [comment] 2023-08-25 13:01
Alright, it should be fixed now. Update your clone to the newest version. The problem was that the subprocess call which starts the reddit video maker was a bit incorrect. Windows wasn't bothered by this, seemingly on linux it causes problems.

**Comment by pwnllc** [comment] 2023-08-25 13:51
Cool, thanks!

**Closed as completed** 2023-08-25 13:51 UTC
